module: SwiftSDK
output: docs
clean: true
xcodebuild_arguments: [-workspace, SwiftSDK.xcworkspace, -scheme, SwiftSDK]
sdk: iphoneos
author: Knurld
author_url: https://www.knurld.io/
copyright: Copyright 2016, Intellisis Inc. All rights reserved.
#podspec: KnurldSwiftSDK.podspec
hide_documentation_coverage: true

custom_categories:
  - name: Main Class
    children:
      - KnurldAPI
  - name: Endpoint Families
    children:
      - Authorization
      - Status
      - AppModels
      - Consumers
      - Enrollments
      - Verifications
      - Calls
      - EndpointAnalyses

  - name: Authorization
    children:
      - OAuthCredentials
      - KnurldCredentials
  - name: Status
    children:
      - ServiceStatus
  - name: Application Models
    children:
      - AppModelCreateRequest
      - AppModelEndpoint
      - AppModel
      - AppModelPage
      - AppModelUpdateRequest
  - name: Consumers
    children:
      - ConsumerCreateRequest
      - ConsumerEndpoint
      - Consumer
      - ConsumerPage
      - ConsumerUpdateRequest
      - ConsumerAuthenticateRequest
      - ConsumerCredentials
      - ConsumerToken
  - name: Enrollments
    children:
      - EnrollmentCreateRequest
      - EnrollmentEndpoint
      - Enrollment
      - EnrollmentPage
      - EnrollmentApplication
      - EnrollmentConsumer
      - EnrollmentInstructions
      - EnrollmentData
      - EnrollmentInterval
      - EnrollmentUpdateRequest
  - name: Verifications
    children:
      - VerificationCreateRequest
      - VerificationEndpoint
      - Verification
      - VerificationPage
      - VerificationApplication
      - VerificationConsumer
      - VerificationInstructions
      - VerificationData
      - VerificationInterval
      - VerificationUpdateRequest
  - name: Calls
    children:
      - CallCreateRequest
      - CallEndpoint
      - Call
      - CallPage
      - CallTerminateRequest
  - name: Endpoint Analyses
    children:
      - URLEndpointAnalysisCreateRequest
      - FileEndpointAnalysisCreateRequest
      - EndpointAnalysisEndpoint
      - EndpointAnalysis
      - EndpointAnalysisInterval
  - name: Miscellaneous
    children:
      - HTTPRequestError
